# Copyright 2022 Matthew Nykamp All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: "2.0"
info:
  title: "Specialist Arena Matches"
  description: "Add a record of a game of Specialist Arena."
  version: "1.0.0"
# This field will be replaced by the deploy_api.sh script.
host: "YOUR-PROJECT-ID.appspot.com"
schemes:
  - "https"
paths:
  "/match":
    post:
      description: "Add a match to the database."
      parameters:
        - name: matchData
          required: true
          in: body
          schema:
            $ref: '#/definitions/match'
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "There was malformed data in the request."

definitions:
  match:
    type: object
    properties:
      date:
        type: string
      patch:
        type: string
      settings:
        type: integer
      player:
        type: array
        items:
          type: object
          properties:
            steamid:
              type: integer
            kills:
              type: integer
            deaths:
              type: integer
            assists:
              type: integer
            team:
              type: integer
            abilities:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  level:
                    type: integer