# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmatch.proto\"\xc3\x02\n\x0bMatchRecord\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\x03\x12\r\n\x05patch\x18\x03 \x01(\t\x12\x10\n\x08settings\x18\x04 \x01(\x05\x12)\n\x06player\x18\x05 \x03(\x0b\x32\x19.MatchRecord.PlayerRecord\x1a\xc7\x01\n\x0cPlayerRecord\x12\x0f\n\x07steamid\x18\x01 \x01(\x05\x12\r\n\x05kills\x18\x02 \x01(\x05\x12\x0e\n\x06\x64\x65\x61ths\x18\x03 \x01(\x05\x12\x0f\n\x07\x61ssists\x18\x04 \x01(\x05\x12:\n\tabilities\x18\x05 \x03(\x0b\x32\'.MatchRecord.PlayerRecord.AbilityRecord\x12\x0c\n\x04team\x18\x06 \x01(\x05\x1a,\n\rAbilityRecord\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATCHRECORD._serialized_start=16
  _MATCHRECORD._serialized_end=339
  _MATCHRECORD_PLAYERRECORD._serialized_start=140
  _MATCHRECORD_PLAYERRECORD._serialized_end=339
  _MATCHRECORD_PLAYERRECORD_ABILITYRECORD._serialized_start=295
  _MATCHRECORD_PLAYERRECORD_ABILITYRECORD._serialized_end=339
# @@protoc_insertion_point(module_scope)
